### ISSUE TITLE
Feature request: integration to HA (not HASS.IO)

### ISSUE THREAD

**Issue by arnaupv** [arthurdent75/SimpleScheduler#10]
Hi! Unfortunately, I'm not using HASS.IO now, so I would like to know how to integrate this awesome add-on to my HA. Is it possible?

**Comment by arthurdent75** [comment]
Sadly, no. This is an addon, and add-ons are made for HASS.IO, which by the way is now renamed to "Home Assistant" because the main developers want to bring things in that direction for reliability.
That said, you could try to build a docker container starting from dockerfile, but I can't help you with that.

**Comment by micw** [comment]
Hello,

I was about to write the same request but found this one. Could you (briefly) explain, how the scheduler is tied to HA? Maybe it is possible to create a similar setup with plain HA. If it works for me, I'd contribute a tutorial.

Kind regards,
Michael.

**Comment by micw** [comment]
After reading a bit through the code, I think it should not be too hard to run it with HA. I will try the following:
- deploy the add-on docker container on k8s
- expose the UI on my lan
- write a config
- create a token for my user that I uses instead of the SUPERVISOR_TOKEN
- use the internal service in k8s as API URL
 
Is there anything I missed?

How is authentication done when it is run as official add-on? Does the supervisor (or HA itself) proxy the UI and adds auth?

**Comment by arthurdent75** [comment]
Hi @micw 
all you have to do is change the conf.php file.
You should put there the real HA URL and a "Long-Lived Access Tokens" that you generate.
Also be sure that the samba addon is installed so you can reach in rw the "/share/simplescheduler/" folder.

Basically, you may not need a docker. You could setup a LAMP server and put the PHP code and run it there.

**Comment by micw** [comment]
Thank you for the reply. I'll use docker since I'm already on k8s. I do not understand the samba part (why do i need to access the folder?).

Where can I find the dockerfile?

How does the HA supervisor pass the url and token to the container?

**Comment by arthurdent75** [comment]
> Thank you for the reply. I'll use docker since I'm already on k8s. I do not understand the samba part (why do i need to access the folder?).

https://github.com/arthurdent75/SimpleScheduler#two-words-about-the-stored-data
Anyway, any other location would be fine as long as is located outside your docker.
Otherwise, you will lose all the schedulers any time you rebuild.

> Where can I find the docker image?

It is written in the very first line of the **dockerfile**
https://github.com/arthurdent75/SimpleScheduler/blob/master/Dockerfile

> How does the HA supervisor pass the url and token to the container?

They are written in the conf.php file
https://github.com/arthurdent75/SimpleScheduler/blob/master/rootfs/var/www/html/conf.php
You should clone the repo and replace them in the conf.php

**Comment by micw** [comment]
Thanks. I use a volume for the data. Startup gave me an error because /data/config.json does not exist (I wonder where it would come from when you are on hass.io). I changed the startup script to check if the file exists prior to copy it:

```
if [ -f /data/options.json ]; then
        cp /data/options.json $FOLDER/options.dat
fi
```

I also did a small change to the default conf.php:

```
$HASSIO_URL = getenv('HASSIO_URL') ?: "http://hassio/homeassistant/api";
```

This allows me to run the container without the need to inject my own config.

I'll create a PR for this changes.

| | Where can I find the docker image?
| It is written in the very first line of the dockerfile

I meant, where can I find a released docker image of the scheduler? It seems to me there isn't any and hass.io builds the container itself. Would you be open to auto-build images from your tags (using github action)? I'd provide the required config if you like.

**Comment by micw** [comment]
It's basically working now. Needs some minor tweaks but looks goot for the first attempt :-)

![image](https://user-images.githubusercontent.com/186753/184501964-02a97d79-d626-46c3-835a-485a81084093.png)

**Comment by micw** [comment]
I pushed my changes as PR

**Comment by arthurdent75** [comment]
I'm woking on a bugfix these days. I will include those in the next release.
