### ISSUE TITLE
Temperature selection via HA

### ISSUE THREAD

**Issue by RudiPohlen** [arthurdent75/SimpleScheduler#147]
I use the SimpleScheduler to control my thermostats on the heating system. That works quite well so far.
From a purely visual point of view, I think it would be great if you could also enter a temperature for OFF without switching off the thermostat.
So on at 08:00 22 degrees, off at 23:00 18 degrees.
But why I'm writing here, sometimes I need to adjust the temperatures a little. As long as it's not freezing outside, it's enough for me to set 22 degrees. If it gets cooler, I have to set it to 23 degrees. But if I have to change every switching time like this, it's tedious.
I have made a few controllers under HomeAssistant with which I can set a heating temperature and a setback temperature using a slider. If I could now transfer these values to the Simple Scheduler, that would be perfect.

**Comment by arthurdent75** [comment]
> From a purely visual point of view, I think it would be great if you could also enter a temperature for OFF without switching off the thermostat.

You can use the **TO** option. This option sets the temperature without turning on the thermostat. Using this, if the thermostat is off, it will stay off, but with a different set point. Of course, it works only in the ON field.
e.g. **17:24>TO23.5**

> But why I'm writing here, sometimes I need to adjust the temperatures a little. As long as it's not freezing outside, it's enough for me to set 22 degrees. If it gets cooler, I have to set it to 23 degrees. But if I have to change every switching time like this, it's tedious.
> I have made a few controllers under HomeAssistant with which I can set a heating temperature and a setback temperature using a slider. If I could now transfer these values to the Simple Scheduler, that would be perfect.

You can achieve this in different ways...

One way is to set two schedulers. Duplicate the actual scheduler and change the temperature. This way you have two identical schedulers but with different setpoints. Then, you choose which one has to stay enabled. You can also automate this using an automation and the MQTT feature of SimpleScheduler, to get the switches for both the schedulers.

Another way is to create a script that sets the temperature of the thermostat based on your slider, and then call the script from SimpleScheduler.

Last but not the least, you can try the new beta version, which has a new feature, which is a "condition-based" scheduler.
![image](https://github.com/arthurdent75/SimpleScheduler/assets/60071192/137c7e58-fc45-4cc1-baab-16b7a2214a91)
It will execute the ON actions on the left if the template condition returns TRUE, otherwise it executes the one in the right column

Take your pick... 😉

**Comment by RudiPohlen** [comment]
I am aware that I can set the temperature with >TO, but in terms of clarity, the night setback would be better located in the OFF section. But ok, that's the minor problem.

Even more schedulers with the same switching times but different temperatures would tend to make things much less clear and would not be easy to operate.
Switch off the scheduler not required for room 1 and make it invisible, switch on Scheduler2 for room 1 and make it visible for all rooms. 

Scripting would certainly be a better option, but here too there is the problem of confusion. I can then only see that a script is started at a certain time. Unfortunately, I can't see which temperature is set in the SimpleScheduler overview.
The number of scripts does not increase the clarity of the scripts either. 6 rooms = 12 scripts.

Don't get me wrong. The SimpleScheduler is great. But I'm just trying to find a suitable integration for me that is also clear.
Would it be possible that in one of the next versions, the temperatures could be transmitted via MQTT and not just an ON and OFF?

The BETA version could possibly work. I'll have to take a closer look.

**Comment by arthurdent75** [comment]
> Don't get me wrong. The SimpleScheduler is great. But I'm just trying to find a suitable integration for me that is also clear.

I never had the presumption that SimpleScheduler can please you all. 
If you find something else that fits your needs, good for you! 😉 
The main concept around this addon is "simple"... 
Indeed, I think it is starting to become a little too complicated.


> Would it be possible that in one of the next versions, the temperatures could be transmitted via MQTT and not just an ON and OFF?

I was already thinking about reading some values (temperature, light color, and so on) from an entity...   but the real deal is how to fit that into the time field and keep it clear in the main view...

> The BETA version could possibly work. I'll have to take a closer look.

Glad to hear that!
