### ISSUE TITLE
Trigger Automations

### ISSUE THREAD

**Issue by moorgrove** [arthurdent75/SimpleScheduler#153]
I can choose an automation in the device list but instead of turning the automation on and off I would like to trigger the automation. I have an automation that turn on different lights every morning depending on different parameters like who is home, if a specific room should be excluded, if the sun already is up, etc. It would be nice to use the GUI in Simple Scheduler to easily change the time the automation triggers if we need the adjust the time.

**Comment by arthurdent75** [comment]
The concept of automation is to run actions on triggers per se. Otherwise what you need is a script.
If you want to run actions, even with conditions, you should create a script.
So, you can collect all the actions inside a script, then you can call the script both from the automation and the scheduler addon.
