### ISSUE TITLE
Climate Control Bug - Unexpected Mode Change When Adjusting Temperature

### ISSUE THREAD

**Issue by htht2001** [arthurdent75/SimpleScheduler#168]
I encountered an issue with the climate control system when attempting to change the air conditioner’s temperature.

Steps to reproduce:

The air conditioner is set to cooling mode at 19 degrees.
I use the automation 14:26>T21 to raise the temperature to 21 degrees.
Observed behavior:
Occasionally, the air conditioner also changes its mode of operation from cooling to heating at 21 degrees, instead of just adjusting the temperature.

Expected behavior:
The air conditioner should only raise the temperature to 21 degrees while remaining in cooling mode.

Let me know if you need any further details or logs.

**Comment by arthurdent75** [comment]
Hi @htht2001, 
try to use this command **14:26>TO21**  ( TO = Temperature Only)
This function was added due to a similar behavior from another user (#51). Every climate works differently.

If this doesn't solve the issue, you can enable the _debug mode_ in the settings and post the log section where the command to the climate is being called. 
Remember to disable the debug mode ASAP, because the log can become huge.

**Comment by htht2001** [comment]
There is an understandable problem here
in the climate
There is no such thing as just activation
A session must come with a state defined using the set_hvac_mode
