### ISSUE TITLE
Daylight saving time problem

### ISSUE THREAD

**Issue by Boia11** [arthurdent75/SimpleScheduler#26]
I set power off time schedule to 2 a.m. but ofter DST change the device power off at 1 a.m.

![Screenshot_20201027-013833__03.jpg](https://user-images.githubusercontent.com/10048197/97243466-b1f5c600-17f6-11eb-81d7-1cd087d987f3.jpg)

![Screenshot_20201027-014805__02.jpg](https://user-images.githubusercontent.com/10048197/97243500-c1750f00-17f6-11eb-878c-d0348c7af343.jpg)

![Screenshot_20201027-014714__01.jpg](https://user-images.githubusercontent.com/10048197/97243511-c5a12c80-17f6-11eb-9834-3c5c5d20e0e0.jpg)

**Comment by arthurdent75** [comment]
That's odd. 
Surely is related to DST, but it seems to me a mattero of a missing time sync instead of a real addon issue.
I have three instance of this addon (one for real use and two for testing/development) and they all worked flawless, since the night that DST changed.
Please, try to reboot the whole HA server, if you can.
Which hardware do you use? What kind of installation do you have (hass, vm, docker, core, etc)?

**Comment by Boia11** [comment]
Nothing "my error"...the Sonoff Cloud has reactivated autonomously the schedule and they have problem with DTS.
I noticed this because at 1am I updated the server and HA was turned off
