### ISSUE TITLE
[request] Add cover entities

### ISSUE THREAD

**Issue by papinist** [arthurdent75/SimpleScheduler#49]
Hi,
it would be cool if you could add scheduling for Cover entities, with ability to set a % for opening (ON) and closing (OFF).

Thanks!

**Comment by protivizion** [comment]
Is one of main feature why I installed this scheduler, but it is not compatible with covers. It is more simpler and much better to use than other I try before. So I use it without cover. 
I need this feature too.

One more thing is disable schedulers via main web page, not opening each scheduler. And possibility to disable/enable via other automatizations. Because on any holiday all family wake up as at workday, house start to turn lights etc.

**Comment by arthurdent75** [comment]
Covers added in version 0.33

@protivizion what you ask is already in my mind. There's no way I could do that from an addon. To achieve that I have to create an integration, which is completely different from an addon.
