### ISSUE TITLE
UI not displayed correctly without internet connection

### ISSUE THREAD

**Issue by TsvetanMarinov** [arthurdent75/SimpleScheduler#66]
I like your add-on. It makes scheduling a breeze, but I just discovered the UI is not working correctly without internet connection. It seems that part of the web page is fetched from the internet. I am trying to run HA without constant internet connection and this is a deal breaker for me. Is is possible to store the files in the container of the add-on?

**Comment by arthurdent75** [comment]
You are right. The UI calls a number of libraries from the internet such as bootstrap, jquery and material icons.
This is a common way of doing it because when you load the page outside your home, these files load faster from their CDN than from your home server.
So I'm not entirely sure that this could be considered an enhancement rather than a disadvantage.

Maybe I could achieve this with a configuration option. I will think about that...

**Comment by TsvetanMarinov** [comment]
Thank you, it is appreciated. I understand my use case is a bit of unusual one.

**Comment by arthurdent75** [comment]
@TsvetanMarinov I try to implement what you asked for.
Sadly, I was optimist about that, because I just call 5 libraries (2 CSS and 3 JS) so I thought it would be easy to include them into  the container.
What happens in reality is that these libraries call other files, so I had to retrieve more than 15 files.
I still try to do that, but HA wasn't able to load them, I suppose because of their mime type.
So I give up for the moment. Maybe in the future I will study a different way to do that, maybe with an internal proxy.
