### ISSUE TITLE
Gives some error after upgrade

### ISSUE THREAD

**Issue by fabiancsalad** [arthurdent75/SimpleScheduler#7]
0.13 gives in the first line:
Warning: file_put_contents(/share/simplescheduler/sun.dat): failed to open stream: Permission denied in /var/www/html/lib.php on line 221

**Comment by arthurdent75** [comment]
I'm not able to reproduce the issue. I try on 3 different installations.
I will work to catch the error and log it instead of showing it up.

**Comment by fabiancsalad** [comment]
Hi,

Thanks for your reply! I've resetted the config to defaults and the Warning
message disappeared. Earlier I edited the config to localize the language.
One more thing. When I add new Schedule, It should be better to put the
days below the time not next to it, and use the first 3 characters of the
day (e.g. in our language Wednesday starts with "Sze" and Saturday with
"Szo". Also in this case the "sunset, sunrise optin can be seen in the
field of the time.
Plus Sunset/Sunrise radio button would be better, and in this case the time
field can be disabled or which is better can be used for shifting to
Sunset/Sunrize (e.g. Sunset is selected and the time field contains
-01:12:00 means "1 hour 12 minutes before sunset",

Br,
Gábor (alias fabiancsalad)

**Comment by arthurdent75** [comment]
> Thanks for your reply! I've resetted the config to defaults and the Warning message disappeared. Earlier I edited the config to localize the language. 

I still don't understand while it is happening. By the way, I will avoid this behavior in the next release, which is almost ready.
> When I add new Schedule, It should be better to put the days below the time not next to it, 

I prefer to have a more linear appearance because when the schedules are many, a thin row is better. By the way, in a smaller browser or in mobile app, they already stack in a vertical way.

> use the first 3 characters of the day (e.g. in our language Wednesday starts with "Sze" and Saturday with "Szo". 

It would be difficult to fit 3 letters in the circles. I think that day's order should compensate for the repetition. In Italian many times we have only one letter for weekdays, and they look like "L M M G V S D" because we have _Martedì_ (Tuesday) and _Mercoledì_ (Wednesday). The order does the magic ;)

> Plus Sunset/Sunrise radio button would be better, and in this case the time
field can be disabled or which is better can be used for shifting to Sunset/Sunrize (e.g. Sunset is selected and the time field contains -01:12:00 means "1 hour 12 minutes before sunset",

It requires a little more effort to achieve, much more than the whole scheduling script. You're not the first one to make this request. I will think about that, but not now.
