### ISSUE TITLE
Schedules not executing

### ISSUE THREAD

**Issue by sweichbr** [arthurdent75/SimpleScheduler#90]
I haven't used this add on for a bit. Now tried again and schedule are not executing.

I am getting  the following error in the UI
![Screenshot_20221120_001735_Home Assistant](https://user-images.githubusercontent.com/43111308/202886930-198af64e-8456-41f5-a783-3d8ce583a756.jpg)

**Comment by arthurdent75** [comment]
First of all, you see those errors because you set "DEBUG: True" in the addon options, otherwise you won't see any error.
Based on the few clues from your image, it doesn't seem to be an issue. 
The leading causes could be:

- You removed the entity used by the scheduler
- You delete the JSON files from the _/share/simplescheduler_ folder

By the way, a new release will come out in the following weeks.
I'm closing this issue because the new release is completely rewritten from scratch so, basically, there is nothing to fix here.

Feel free to open another issue if you will find any errors in the next release.

Cheers
